### ISSUE TITLE
Build StockDetail Screen - Consume API data for a single Stock (provided via prop)

### ISSUE THREAD

**Issue by veeepi** [BCIT-SSD-2020-21/mobile-project-team-2#33]

**Comment by jianmingtu** [comment]
![](https://i.imgur.com/0o5CYwM.png)

**Comment by jianmingtu** [comment]
1) Users can navigate to the stock detail screen by tapping the Portfolio entry or WatchList entry on the Portfolio screen, as well as tapping the searching result entry from the searching screen.
2) Users can navigate to the Buy or Selll screen by clicking on Buy or Sell button. If the user does not have the stock in his portfolio the Sell button will be disabled.
3) clicking on watch button will add the stock to user portfolio' s watch list
4) show stock  from finnhub's profile2 and quote
