### ISSUE TITLE
StockDetail Screen, conditional render User functionality (User ? enable Buy/Sell)

### ISSUE THREAD

**Issue by veeepi** [BCIT-SSD-2020-21/mobile-project-team-2#34]

**Comment by jianmingtu** [comment]
the work has been done in issue #33 https://github.com/BCIT-SSD-2020-21/mobile-project-team-2/issues/33.
Users can navigate to the Buy or Selll screen by clicking on Buy or Sell button.  If the user does not have the stock in his portfolio the Sell button will be disabled.
