### ISSUE TITLE
Route to StockDetail Screen from Portfolio and Search Screen

### ISSUE THREAD

**Issue by veeepi** [BCIT-SSD-2020-21/mobile-project-team-2#35]

**Comment by jianmingtu** [comment]
the work has been done in issue #33 https://github.com/BCIT-SSD-2020-21/mobile-project-team-2/issues/33.
Users can navigate to the stock detail screen by tapping the Portfolio entry or WatchList entry on the Portfolio screen,  as well as tapping the searching result entry from the searching screen.
